{"name": "Проверка авторизации курьера с неверным логином", "status": "passed", "description": "Проверяем, что при отправке запроса с неверным логином приходит ошибка", "start": 1720026148026, "stop": 1720026148114, "uuid": "f2e9e167-c9fb-4017-85b6-65496b59e9cb", "historyId": "ac05f8f2b041f62c7727b84aa71195ae", "testCaseId": "ac05f8f2b041f62c7727b84aa71195ae", "fullName": "tests.test_login_courier.TestLoginCourier#test_login_courier_with_wrong_login", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "DESKTOP-U9M0S31"}, {"name": "thread", "value": "5252-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}